# Configuration for a static website.
#
# https://cloud.google.com/appengine/docs/standard/python3/config/appref

runtime: python37

handlers:

  # Supports cache-busting so clients always get fresh statics.
  - url: /static/[a-z0-9]+/
    static_dir: static
    expiration: 7d
    secure: always
    http_headers:
      Strict-Transport-Security: "max-age=2592000; includeSubdomains"
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"

  - url: /.*
    script: auto
    secure: always

env_variables:
  FLASK_SETTINGS_FILENAME: "settings.py"
